### ISSUE TITLE
Explore and document ECS Exec usage with Incubator

### ISSUE THREAD

**Issue by JasonEb** [hackforla/incubator#80]
### Overview

As a developer/system administrator/tech lead, I'd like documentation showcasing how to securely interact with Fargate applications on Incubator.

Currently the HFLA's incubator leverages ECS + Fargate to deploy software. A common use case would be how to connect into a deployed Fargate instance in order to manage its contents. 

https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/

### Action Items

- [ ] Determine service costs
- [ ] Determine prerequisites
- [ ] Document local setup
- [ ] Document usage
- [ ] Create article on Incubator/Ops wiki 

### Resources/Instructions

[Resources](https://github.com/hackforla/ops/wiki)
[AWS Exec article](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/)
[AWS ECS Exec for Debugging](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html)

**Comment by sudhara** [comment]
Per conversation at the leads meetings with @ExperimentsInHonesty , @chelseybeck , @RSkuma , @ale210 this issue is not needed. The reason being, no one should be able to update the contents of the ECS instance other than the GitHub pipeline CI/CD. We can revisit this later if it's needed in the future.
